#cloud-config

write_files:
# setup script
  - path: "/root/setup.preflight.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_preflight_sh_content}
  - path: "/root/setup.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${setup_template_sh_content}
  - path: "/root/deploy.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${deploy_template_content}
  - path: "/etc/systemd/system/dotnet-app.service"
    permissions: "0644"
    content: |
      [Unit]
      Description=Demo ASP.Net service
      After=network.target

      [Service]
      Type=simple
      WorkingDirectory=/app/myOracleQuickstartWebApp/bin/Release/net5.0/linux-x64/publish/
      ExecStart=/usr/bin/dotnet /app/myOracleQuickstartWebApp/bin/Release/net5.0/linux-x64/publish/myOracleQuickstartWebApp.dll --urls "http://*:5000"
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=dotnet-app-demo
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

      [Install]
      WantedBy=multi-user.target

runcmd:
 - echo "Running prep scripts..."
 - /root/setup.preflight.sh
 - echo "Finished prep scripts."
 - echo "Starting DotNet App..."
 - systemctl enable dotnet-app
 - systemctl start dotnet-app

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init-output.log'}